### PR TITLE
Schema2020

### PR DESCRIPTION
**Pull request by tucotuco**
Extension schema with non-breaking element additions for comments and examples matching Darwin Core. Anticipates updates to core and extensions to make them current with the standard. Comments and examples are now non-normative and separate in DwC term definitions. This change reflects that and allows comments and examples to be shared in the extension definitions, and thereby potentially in the IPT as well.

### CODE REVIEW

**Comment by tucotuco** [comment]
I'll wait on a merge for this one before submitting the pull requests for the changes to the cores and extensions. First of all, it will avoid all the repeated commits that have already been merged from elsewhere, and second it will let me know if I can proceed with the two new elements "comment" and "examples".

**Comment by timrobertson100** [comment]
@MattBlissett  I think the schema looks fine here. Should we start promoting a rebase approach to keep the commit history cleaner do you think?

**Comment by MattBlissett** [comment]
"Squash and merge" would result in a branch starting in the same place, but with only one commit, then merge it to master.  "Rebase and merge" would add a single commit to master.

Squash and merge is a bit closer to reality (it keeps the timeline closer to what happened), rebasing gives a single list of commits.  I don't mind either way.

**Comment by MattBlissett** [comment]
We've discussed merging this, but no-one has pressed the button. I'll merge it now, thanks for your patience John.

**Pull request merged**
