### PR TITLE
Added Protocol to model to cover conabio-agro use case.

### PR DESCRIPTION
**Pull request by tucotuco**

### CODE REVIEW

**Review by mike-podolskiy90 — CHANGES_REQUESTED** [review]
We have to update identifiers and URLs in the individual table schema files too

**Review by mike-podolskiy90 — APPROVED** [review]

**Comment by mike-podolskiy90** [comment]
Thank you John! I think we can merge it. My only concern is that I suspect that all the existing extended-occurrence resources will break (basically this is a new schema), so I guess we should delete them and start from scratch.

**Comment by tucotuco** [comment]
Is this one of them (I can't see it)?  https://dwc2-ipt.gbif-uat.org/resource?r=test_joerg

Are there others? Curious about what they are.

Can't promise there won't be more changes. I am testing mapping (https://github.com/gbif/model-dwca-v2) to the WIP schema and making changes as I find things. I have many more in progress that are not in that repository, and the ones there are still subject to change.

**Comment by mike-podolskiy90** [comment]
Yes, it is. There are also two more from Tim.

Do you need your password reset to access the Management tab in the IPT to have a look?

**Comment by tucotuco** [comment]
> Do you need your password reset to access the Management tab in the IPT to have a look?

If I have an account on that one, yes please. I don't know that I do have an account there.

**Review by mike-podolskiy90 — APPROVED** [review]

**Comment by mike-podolskiy90** [comment]
@tucotuco Thank you John, seems fine to me.

I'll delete all the resources from https://dwc2-ipt.gbif-uat.org/ since they won't work anymore because of schema change

**Comment by tucotuco** [comment]
Excellent, thank you!

**Pull request merged**
